harness:
  database:
    auto: true
    local_expose: true
    type: postgres
    size: 2Gi
    resources:
      limits:
        cpu: '0.50'
      requests:
        cpu: '0.25'
  dependencies:
    build: []
    hard: []
  deployment:
    auto: true
    port: 8080
    replicas: 1
    resources:
      limits:
        cpu: '0.50'
        memory: 500M
      requests:
        cpu: '0.25'
        memory: 32M
  livenessProbe: {path: /api/live}
  readinessProbe: {path: /api/ready}
  secured: false
  service: {auto: true, port: 8080}
  subdomain: celegans
  test:
    api:
      autotest: true
      checks: [all]
      enabled: true
  # uri_role_mapping:
  # - require-any-role: true
  #   roles: ['celegans:celegans-administrator', 'celegans:celegans-manager',
  #     'celegans:celegans-user']
  #   uri: /*
  # use_services:
  # - {name: common}