# Generated by Django 5.0.3 on 2025-06-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_viewerconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synapse",
            name="connection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="synapse_entities",
                to="api.connection",
            ),
        ),
    ]
