# Generated by Django 5.0.3 on 2025-08-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_synapse_size_alter_synapse_connection"),
    ]

    operations = [
        migrations.AddField(
            model_name="synapse",
            name="position",
            field=models.JSONField(null=True),
        ),
    ]
