name: Build Frontend

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21.7
      - name: Install dependencies
        working-directory: applications/visualizer/frontend
        run: yarn install 
      - name: Build App
        working-directory: applications/visualizer/frontend
        run: npm run build
