name: Python Tests

on: [push, pull_request]

jobs:
  pytest-visualizer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./applications/visualizer/backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies and dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Test with pytest
        run: |
          python -m pytest
  pytest-ingestion:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ingestion
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies and dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install .
      - name: Test with pytest
        run: |
          python -m pytest